version: '3'    

volumes:
  static:
  database:
  esdata:

services:
  myblog:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: myblog
    container_name: myblog
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - envs/.production
    ports:
      - "8000:8000"
    command: /start.sh
    depends_on: #依赖 需要先启动elasticsearch
      - elasticsearch

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: myblog_nginx
    container_name: myblog_nginx
    volumes:
      - static:/apps/myblog/static
    ports:
      - "80:80"
      - "443:443"
    depends_on: #依赖 需要先启动myblog
      - myblog

  elasticsearch:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: elasticsearch
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   #ulimits:
   #  memlock:
   #    soft: -1
   #    hard: -1
   #  nproc: 65536
   #  nofile:
   #    soft: 65536
   #    hard: 65536
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G